name: Infrastructure Deployment

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'

env:
  AWS_REGION: us-west-2
  NODE_VERSION: '20.x'

jobs:
  infrastructure-validation:
    name: Infrastructure Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Run infrastructure tests
        run: npm run test --workspace=infrastructure

      - name: CDK security check
        run: |
          cd infrastructure
          # Check for hardcoded secrets
          grep -r "AKIA\|password\|secret" lib/ bin/ || echo "No hardcoded secrets found"

      - name: Security controls validation
        run: |
          cd infrastructure
          echo "Validating security controls in CDK synthesis..."

          # Generate CDK output for validation
          npm run synth -- --context environment=dev > cdk-output.json

          # Check for security groups
          if grep -q "AWS::EC2::SecurityGroup" cdk-output.json; then
            echo "✅ Security Groups found"
          else
            echo "❌ CRITICAL: No Security Groups found - infrastructure exposed"
            exit 1
          fi

          # Check for CloudTrail
          if grep -q "AWS::CloudTrail::Trail" cdk-output.json; then
            echo "✅ CloudTrail found"
          else
            echo "❌ CRITICAL: No CloudTrail found - no audit logging"
            exit 1
          fi

          # Check for restrictive security group rules
          if grep -q "0.0.0.0/0" cdk-output.json && grep -q "22\|3389" cdk-output.json; then
            echo "❌ WARNING: Found potentially open SSH/RDP ports"
          fi

          echo "Security validation completed"

      - name: CDK diff for dev environment
        run: |
          cd infrastructure
          npm run diff -- --context environment=dev

      - name: CDK synth validation
        run: |
          cd infrastructure
          npm run synth -- --context environment=dev

  infrastructure-compliance:
    name: Compliance & Security Check
    runs-on: ubuntu-latest
    needs: [infrastructure-validation]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run compliance checks
        run: |
          cd infrastructure
          # Check for required tags
          npm run synth | grep -q "ManagedBy.*CDK" || (echo "Missing ManagedBy tags" && exit 1)

          # Check for encryption
          npm run synth | grep -q "SSEEnabled.*true" || echo "Warning: Check encryption settings"

          # Check for retention policies
          npm run synth | grep -q "RemovalPolicy" || echo "Warning: Check retention policies"

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [infrastructure-validation]
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy infrastructure to dev
        run: |
          cd infrastructure
          npm run deploy -- --context environment=dev --require-approval never

      - name: Validate deployment
        run: |
          # Check if stack deployed successfully
          aws cloudformation describe-stacks --stack-name EC2Manager-dev --region ${{ env.AWS_REGION }}

          # Basic health checks
          echo "✅ Infrastructure deployment successful"

      - name: Output infrastructure details
        run: |
          cd infrastructure
          echo "## Infrastructure Outputs" >> $GITHUB_STEP_SUMMARY
          aws cloudformation describe-stacks --stack-name EC2Manager-dev --region ${{ env.AWS_REGION }} --query 'Stacks[0].Outputs' >> $GITHUB_STEP_SUMMARY

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy infrastructure to staging
        run: |
          cd infrastructure
          npm run deploy -- --context environment=staging --require-approval never

      - name: Run staging validation tests
        run: |
          # Wait for resources to be ready
          sleep 60

          # Check API Gateway
          STACK_NAME="EC2Manager-staging"
          API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text || echo "")

          if [ ! -z "$API_ENDPOINT" ]; then
            curl -f "$API_ENDPOINT/health" || echo "API health check failed (expected for now)"
          fi

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Final production readiness check
        run: |
          cd infrastructure
          # Validate production configuration
          npm run synth -- --context environment=production | grep -q "RemovalPolicy.*RETAIN" || (echo "Production must have RETAIN policies" && exit 1)

      - name: Deploy infrastructure to production
        run: |
          cd infrastructure
          npm run deploy -- --context environment=production --require-approval never

      - name: Production deployment verification
        run: |
          # Comprehensive production checks
          sleep 90

          STACK_NAME="EC2Manager-production"

          # Verify all resources are healthy
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].StackStatus'

          # Check security groups are restrictive
          echo "✅ Production infrastructure deployment completed"

      - name: Notify team
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: '🏗️ Production infrastructure updated successfully!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}